### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by usernamex1x23** [carlosedubarreto/vibe_win_install#10]
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 72, in main
    image_folder, num_frames, img_shape = video_to_images(video_file, return_info=True)
  File "D:\video\3\4\lib\utils\demo_utils.py", line 195, in video_to_images
    subprocess.call(command)
  File "D:\Newfolder\envs\venv_vibe\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Newfolder\envs\venv_vibe\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Newfolder\envs\venv_vibe\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by carlosedubarreto** [comment]
Have you found the problem here?

**Comment by carlosedubarreto** [comment]
Think you solve it yourself... just addin the text here, to know that I actually saw this message 😊
