### ISSUE TITLE
no .torch file. file not found error 

### ISSUE THREAD

**Issue by usernamex1x23** [carlosedubarreto/vibe_win_install#11]
i clossed the last issue after i found out that it had already been ans but the solution did not work for me.
i downloaded both yolov3 files

but when i went to c/user/{user name}/.torch

i found out there was no .torch file 
i made a new folder name it .torch added models and config folders and copied the respected yolov3 filles in each 

tried running
  python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display 
nothing same error 
closed the prompt 
re-opened it. double checked that it was in admin.
reinstalled everything 
nothing same error 
copy past of error 
(venv_vibe) D:\video\3\4>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 72, in main
    image_folder, num_frames, img_shape = video_to_images(video_file, return_info=True)
  File "D:\video\3\4\lib\utils\demo_utils.py", line 195, in video_to_images
    subprocess.call(command)
  File "D:\Newfolder\envs\venv_vibe\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Newfolder\envs\venv_vibe\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Newfolder\envs\venv_vibe\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by carlosedubarreto** [comment]
I dont know if I'm understanding correctly, but seems like the demo_alter didnt find the sample_video.mp4 file
are you running it from the root directory where there is the sample_video.mp4 file?

Asking it just to be sure, because, I dont have an idea of what else could be the problem,,,

**Comment by usernamex1x23** [comment]
yep the same folder where both vibe files where extracted .

Unpack the VIBE github pack to a folder

https://github.com/mkocabas/VIBE/archive/master.zip

unpack the contents of this github to the same folder

https://github.com/carlosedubarreto/vibe_win_install/archive/main.zip

i double checked the the sample video file is in that folder

**Comment by carlosedubarreto** [comment]
What about the ffmpeg "installation"?
Maybe the script is trying to use ffmepg but you hada problem to add ffmepg library folder on the windows path.
So when it tries to run FFMPEG it says that cant find it.

So, please double check the ffmpeg "installation"

with instalation i mean, unpacking the zip file and add the ffmpeg executable folder to windows path.

**Comment by usernamex1x23** [comment]
i had installed frankmocap before so i thought i already had done the step i followed the instruction from the video again and ran into this error 

(base) D:\video\3\4>conda activate venv_vibe

(venv_vibe) D:\video\3\4>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Images saved to "/tmp\sample_video_mp4"
Input video number of frames 300
Downloading files from https://pjreddie.com/media/files/yolov3.weights
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 93, in main
    yolo_img_size=args.yolo_img_size,
  File "D:\Newfolder\envs\venv_vibe\lib\site-packages\multi_person_tracker\mpt.py", line 53, in __init__
    device=self.device, img_size=yolo_img_size, person_detector=True, video=True, return_dict=True
  File "D:\Newfolder\envs\venv_vibe\lib\site-packages\yolov3\yolo.py", line 32, in __init__
    download_url(url, outdir)
  File "D:\Newfolder\envs\venv_vibe\lib\site-packages\yolov3\yolo.py", line 11, in download_url
    subprocess.call(cmd)
  File "D:\Newfolder\envs\venv_vibe\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Newfolder\envs\venv_vibe\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Newfolder\envs\venv_vibe\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by usernamex1x23** [comment]
deleting and remaking .torch folder fixed the above problem but i ran into a new error.

(venv_vibe) D:\video\3\4>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Images saved to "/tmp\sample_video_mp4"
Input video number of frames 300
Running Multi-Person-Tracker
100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.02s/it]
Finished. Detection + Tracking FPS 2.84
Displaying results..
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to C:\Users\Hp/.cache\torch\checkpoints\resnet50-19c8e357.pth
100%|█████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:42<00:00, 2.39MB/s]
WARNING: You are using a SMPL model, with only 10 shape coefficients.
=> loaded pretrained model from 'data/vibe_data\spin_model_checkpoint.pth.tar'
Performance of pretrained model on 3DPW: 56.56075477600098
Loaded pretrained weights from "data/vibe_data/vibe_model_wo_3dpw.pth.tar"
Running VIBE on each tracklet...
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "demo_alter.py", line 405, in <module>
  File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\spawn.py", line 105, in spawn_main
    main(args)
    exitcode = _main(fd)
  File "demo_alter.py", line 152, in main
  File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\spawn.py", line 114, in _main
    for batch in dataloader:
    prepare(preparation_data)
  File "D:\Newfolder\envs\venv_vibe\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
  File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Newfolder\envs\venv_vibe\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Newfolder\envs\venv_vibe\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Newfolder\envs\venv_vibe\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\video\3\4\demo_alter.py", line 22, in <module>
    import torch
  File "D:\Newfolder\envs\venv_vibe\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The paging file is too small for this operation to complete.
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Newfolder\envs\venv_vibe\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function tqdm.__del__ at 0x000001C902E0D558>
Traceback (most recent call last):
  File "D:\Newfolder\envs\venv_vibe\lib\site-packages\tqdm\_tqdm.py", line 931, in __del__
    self.close()
  File "D:\Newfolder\envs\venv_vibe\lib\site-packages\tqdm\_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "D:\Newfolder\envs\venv_vibe\lib\site-packages\tqdm\_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "D:\Newfolder\envs\venv_vibe\lib\site-packages\tqdm\_monitor.py", line 52, in exit
    self.join()
  File "D:\Newfolder\envs\venv_vibe\lib\threading.py", line 1041, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by carlosedubarreto** [comment]
Sorry, I didnt encontered this error before... or I dont remember it.
I suggest to take a look at vibes github page, because it seems that it is an issue related to the use of their code.
I'm just trying to make easier to install the dependencies...

link to their issue page
https://github.com/mkocabas/VIBE/issues

**Comment by usernamex1x23** [comment]
thks mate

**Comment by firingthoughts** [comment]
i'm having the same problem.. This command doesn't work either. 

"# Run on a YouTube video
python demo.py --vid_file https://www.youtube.com/watch?v=wPZP8Bwxplo --output_folder output/ --display"

**Comment by h0000c** [comment]
I also encountered a similar problem, I am sure I have added the ffmpeg executable folder to windows path.
1. Are you running on win10?
2. How to delete and recreate the .torch folder?
Thank you very much if you can spend your precious time advising you.

**Comment by carlosedubarreto** [comment]
Hi @h0000c , sorry for the late answer...
Today my day is very busy 😅

I saw your previous question, maybe solving that other problem might resolve this issue you are having here.

I added the answer on the other question, but to help other people in the future, I'll also leave it here
https://github.com/carlosedubarreto/vibe_win_install/issues/5

**Comment by taositing** [comment]
I encountered the same problem, did you solve it?
