### ISSUE TITLE
No sample video output

### ISSUE THREAD

**Issue by firingthoughts** [carlosedubarreto/vibe_win_install#13]
**Hello, I'm trying to run the "sample_video.mp4" or any video and i get this result. Is it because i have AMD GPU? (5700 XT).**

Displaying results..
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 108, in main
    use_residual=True,
  File "E:\vibe\VIBE-master\lib\models\vibe.py", line 147, in __init__
    checkpoint = torch.load(pretrained)
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\torch\serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\torch\serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\torch\serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\torch\serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\torch\serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\torch\serialization.py", line 116, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by firingthoughts** [comment]
**And when i ran a youtube video it came up with this.**

(venv_vibe) E:\vibe\VIBE-master>python demo.py --vid_file https://www.youtube.com/watch?v=wPZP8Bwxplo --output_folder output/ --display
Traceback (most recent call last):
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\platform\egl.py", line 70, in EGL
    mode=ctypes.RTLD_GLOBAL
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 33, in <module>
    from lib.utils.renderer import Renderer
  File "E:\vibe\VIBE-master\lib\utils\renderer.py", line 19, in <module>
    import pyrender
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\pyrender\light.py", line 11, in <module>
    from .texture import Texture
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\pyrender\texture.py", line 8, in <module>
    from OpenGL.GL import *
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "E:\Users\Firing\miniconda3\envs\venv_vibe\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 22, 'The specified module could not be found', None, 126, None, 'EGL', None)

**Comment by carlosedubarreto** [comment]
I never tested the youtube function.
But lets narrow down the problem.

The  other way, using a mp4, does it works with you?

**Comment by firingthoughts** [comment]
Hello, no, it doesn't. That's the first issue in my post

**Comment by carlosedubarreto** [comment]
Please, can you run the installation again and put here all that is shown?

I'm about to go sleep but I'll look at it in the morning

**Comment by firingthoughts** [comment]
Like install vibe again? It was installed correctly i think

**Comment by carlosedubarreto** [comment]
yes, to just tun the installation bat again, in the created enviroment.

This is important to see where is the error.
what part of the installation failed.

Because if you are having this issue using Vibe, is because something didnt go right on the installation.

**Comment by Anitazyx** [comment]
You need to modify the statements in the lib/models/vibe.py file
torch.load(pretrained)
torch.load(pretrained,map_location='cpu')

**Comment by firingthoughts** [comment]
> 
> 
> You need to modify the statements in the lib/models/vibe.py file
> torch.load(pretrained)
> torch.load(pretrained,map_location='cpu')

I updated GPU drivers and it worked for a brief second, it seems to be a problem with the torch.load file indeed.  What do I change those statements to? To "(pretrained,map_location='cpu')"?
