### ISSUE TITLE
FileNotFoundError: [WinError 2] - weights and config are in correct folder

### ISSUE THREAD

**Issue by vogues** [carlosedubarreto/vibe_win_install#21]
(venv_vibe) E:\OneDrive\Band\Art\Blender\MOCAP\App\VIBE>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 72, in main
    image_folder, num_frames, img_shape = video_to_images(video_file, return_info=True)
  File "E:\OneDrive\Band\Art\Blender\MOCAP\App\VIBE\lib\utils\demo_utils.py", line 195, in video_to_images
    subprocess.call(command)
  File "X:\Apps\anaconda\envs\venv_vibe\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "X:\Apps\anaconda\envs\venv_vibe\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "X:\Apps\anaconda\envs\venv_vibe\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\My_bl\.torch\config\yolov3.cfg
C:\Users\My_bl\.torch\models\yolov3.weights

**Comment by carlosedubarreto** [comment]
Sorry I dont use VIbe for more than a year...
The best I can do is suggest you to take a look at this issue, it might help you

https://github.com/carlosedubarreto/vibe_win_install/issues/5
