### ISSUE TITLE
Errors when running prepare_data.bat

### ISSUE THREAD

**Issue by Roee-Kislevski** [carlosedubarreto/vibe_win_install#30]
Hi
Whenever I try to run prepare_data.bat, I get:

> (venv_vibe) C:\MOCAP\VIBE>prepare_data.bat
> 
> (venv_vibe) C:\MOCAP\VIBE>md data
> A subdirectory or file data already exists.
> 
> (venv_vibe) C:\MOCAP\VIBE>cd data
> 
> (venv_vibe) C:\MOCAP\VIBE\data>gdown "https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r"
> Traceback (most recent call last):
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\Scripts\gdown.exe\__main__.py", line 7, in <module>
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\gdown\cli.py", line 61, in main
>     quiet=args.quiet,
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\gdown\download.py", line 52, in download
>     res = sess.get(url, stream=True)
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\requests\sessions.py", line 602, in get
>     return self.request("GET", url, **kwargs)
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\requests\sessions.py", line 575, in request
>     prep = self.prepare_request(req)
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\requests\sessions.py", line 498, in prepare_request
>     hooks=merge_hooks(request.hooks, self.hooks),
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\requests\models.py", line 368, in prepare
>     self.prepare_url(url, params)
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\requests\models.py", line 440, in prepare_url
>     f"Invalid URL {url!r}: No scheme supplied. "
> requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
> 
> (venv_vibe) C:\MOCAP\VIBE\data>cd ..
> 
> (venv_vibe) C:\MOCAP\VIBE>echo #### Extract the files from vibe_data ###
> #### Extract the files from vibe_data ###
> (venv_vibe) C:\MOCAP\VIBE>python unzip_vibe_data.py
> Traceback (most recent call last):
>   File "unzip_vibe_data.py", line 6, in <module>
>     with ZipFile('vibe_data.zip', 'r') as zipObj:
>   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\zipfile.py", line 1240, in __init__
>     self.fp = io.open(file, filemode)
> FileNotFoundError: [Errno 2] No such file or directory: 'vibe_data.zip'
> 
> (venv_vibe) C:\MOCAP\VIBE>copy data\vibe_data\sample_video.mp4 .
> The system cannot find the path specified.
> 
> (venv_vibe) C:\MOCAP\VIBE>echo ### creating place for torch model ###
> ### creating place for torch model ###
> 
> (venv_vibe) C:\MOCAP\VIBE>md \Users\igal\.torch\models
> A subdirectory or file \Users\igal\.torch\models already exists.
> 
> (venv_vibe) C:\MOCAP\VIBE>copy data\vibe_data\yolov3.weights \Users\igal\.torch\models
> The system cannot find the path specified.
> 
> (venv_vibe) C:\MOCAP\VIBE>echo ### creating place for yolo config ###
> ### creating place for yolo config ###
> 
> (venv_vibe) C:\MOCAP\VIBE>md \Users\igal\.torch\config
> A subdirectory or file \Users\igal\.torch\config already exists.
> 
> (venv_vibe) C:\MOCAP\VIBE>copy yolov3.cfg \Users\igal\.torch\config
>         1 file(s) copied.

I'd appreciate help :)

**Comment by carlosedubarreto** [comment]
Hello @Roee-Kislevski ,

sorry I dont use vibe for so long...
And let me suggest you something else.

today you can use much better codes for animation creation from video, such as easymocap monocular and 4d humans.

If you like, I also did addons for blender where you can do all the progress in blender and dont have to worry installing the python stuff (its configured for the addon to do that for you.)

You can have free version of those addons, that will bring the core funcionalities as you were installgin the code from github,. the paid versions brings more things, that the core code doesnt have.

ig you'd like to test them you can find on my gumroad.
https://carlosedubarreto.gumroad.com/

some of the download says its paid, but look at the description, most of them there is a code to get for free (I had to put a price because of the size of the files)

**Comment by Roee-Kislevski** [comment]
> Hello @Roee-Kislevski ,
> 
> sorry I dont use vibe for so long... And let me suggest you something else.
> 
> today you can use much better codes for animation creation from video, such as easymocap monocular and 4d humans.
> 
> If you like, I also did addons for blender where you can do all the progress in blender and dont have to worry installing the python stuff (its configured for the addon to do that for you.)
> 
> You can have free version of those addons, that will bring the core funcionalities as you were installgin the code from github,. the paid versions brings more things, that the core code doesnt have.
> 
> ig you'd like to test them you can find on my gumroad. https://carlosedubarreto.gumroad.com/
> 
> some of the download says its paid, but look at the description, most of them there is a code to get for free (I had to put a price because of the size of the files)

Thank you so much! I'll try it out

**Comment by ivanduminika707-collab** [comment]
> Hi
> 
> Whenever I try to run prepare_data.bat, I get:
> 
> 
> 
> > (venv_vibe) C:\MOCAP\VIBE>prepare_data.bat
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE>md data
> 
> > A subdirectory or file data already exists.
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE>cd data
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE\data>gdown "https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r"
> 
> > Traceback (most recent call last):
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\runpy.py", line 193, in _run_module_as_main
> 
> >     "__main__", mod_spec)
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\runpy.py", line 85, in _run_code
> 
> >     exec(code, run_globals)
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\Scripts\gdown.exe\__main__.py", line 7, in <module>
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\gdown\cli.py", line 61, in main
> 
> >     quiet=args.quiet,
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\gdown\download.py", line 52, in download
> 
> >     res = sess.get(url, stream=True)
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\requests\sessions.py", line 602, in get
> 
> >     return self.request("GET", url, **kwargs)
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\requests\sessions.py", line 575, in request
> 
> >     prep = self.prepare_request(req)
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\requests\sessions.py", line 498, in prepare_request
> 
> >     hooks=merge_hooks(request.hooks, self.hooks),
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\requests\models.py", line 368, in prepare
> 
> >     self.prepare_url(url, params)
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\site-packages\requests\models.py", line 440, in prepare_url
> 
> >     f"Invalid URL {url!r}: No scheme supplied. "
> 
> > requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE\data>cd ..
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE>echo #### Extract the files from vibe_data ###
> 
> > #### Extract the files from vibe_data ###
> 
> > (venv_vibe) C:\MOCAP\VIBE>python unzip_vibe_data.py
> 
> > Traceback (most recent call last):
> 
> >   File "unzip_vibe_data.py", line 6, in <module>
> 
> >     with ZipFile('vibe_data.zip', 'r') as zipObj:
> 
> >   File "C:\Users\igal\miniconda3\envs\venv_vibe\lib\zipfile.py", line 1240, in __init__
> 
> >     self.fp = io.open(file, filemode)
> 
> > FileNotFoundError: [Errno 2] No such file or directory: 'vibe_data.zip'
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE>copy data\vibe_data\sample_video.mp4 .
> 
> > The system cannot find the path specified.
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE>echo ### creating place for torch model ###
> 
> > ### creating place for torch model ###
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE>md \Users\igal\.torch\models
> 
> > A subdirectory or file \Users\igal\.torch\models already exists.
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE>copy data\vibe_data\yolov3.weights \Users\igal\.torch\models
> 
> > The system cannot find the path specified.
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE>echo ### creating place for yolo config ###
> 
> > ### creating place for yolo config ###
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE>md \Users\igal\.torch\config
> 
> > A subdirectory or file \Users\igal\.torch\config already exists.
> 
> > 
> 
> > (venv_vibe) C:\MOCAP\VIBE>copy yolov3.cfg \Users\igal\.torch\config
> 
> >         1 file(s) copied.
> 
> 
> 
> I'd appreciate help :)

**Comment by carlosedubarreto** [comment]
@ivanduminika707-collab , sorry I think I'm not able to help much on that, itsbeen year since I dont try VIBE, and honestly, today we've got better solutions on the result and even on the processing speed, like 4d humans and recently GVHMR and PromptHMR.

I would suggest to take a look on those.
