### ISSUE TITLE
VIBE BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by alivemachine** [carlosedubarreto/vibe_win_install#4]
Unable to run VIBE anymore today. Even after starting again from scratch and only using provided sample content. Here is what I get:
```
(venv_vibe2) D:\MOCAP02\VIBE>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Images saved to "/tmp\sample_video_mp4"
Input video number of frames 300
Running Multi-Person-Tracker
100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:32<00:00,  3.22it/s]
Finished. Detection + Tracking FPS 9.12
Displaying results..
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
=> loaded pretrained model from 'data/vibe_data\spin_model_checkpoint.pth.tar'
Performance of pretrained model on 3DPW: 56.56075477600098
Loaded pretrained weights from "data/vibe_data/vibe_model_wo_3dpw.pth.tar"
Running VIBE on each tracklet...
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 152, in main
    for batch in dataloader:
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function tqdm.__del__ at 0x000001B3B31B15E8>
Traceback (most recent call last):
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\site-packages\tqdm\_tqdm.py", line 931, in __del__
    self.close()
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\site-packages\tqdm\_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\site-packages\tqdm\_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\site-packages\tqdm\_monitor.py", line 52, in exit
    self.join()
  File "C:\Users\[user]\miniconda3\envs\venv_vibe2\lib\threading.py", line 1041, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```
Attempting to troubleshoot this. Any help welcome!

**Comment by carlosedubarreto** [comment]
Hello @alivemachine 
This error is better to assingn an issue on the Vibes github, because I'm not able to answer you.
The demo_alter.py was created just to give some optimized configs like, remove EGL viewer (that has problems on windows) and set some default numbers that most people were having problems running receiving out of memory errors.

And I never faced this problem you are reporting.
