### ISSUE TITLE
(SOLVED) FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by gqbay** [carlosedubarreto/vibe_win_install#5]
After  python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display 
i got following:

(venv_vibe) D:\AI\VIBE\vibe>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Images saved to "/tmp\sample_video_mp4"
Input video number of frames 300
Downloading files from https://pjreddie.com/media/files/yolov3.weights
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 93, in main
    yolo_img_size=args.yolo_img_size,
  File "C:\Users\Administrator\miniconda3\envs\venv_vibe\lib\site-packages\multi_person_tracker\mpt.py", line 53, in __init__
    device=self.device, img_size=yolo_img_size, person_detector=True, video=True, return_dict=True
  File "C:\Users\Administrator\miniconda3\envs\venv_vibe\lib\site-packages\yolov3\yolo.py", line 32, in __init__
    download_url(url, outdir)
  File "C:\Users\Administrator\miniconda3\envs\venv_vibe\lib\site-packages\yolov3\yolo.py", line 11, in download_url
    subprocess.call(cmd)
  File "C:\Users\Administrator\miniconda3\envs\venv_vibe\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Administrator\miniconda3\envs\venv_vibe\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Administrator\miniconda3\envs\venv_vibe\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by carlosedubarreto** [comment]
Hello.

Try this
https://github.com/carlosedubarreto/vibe_win_install/issues/1

if it doesnt work, try this
https://github.com/carlosedubarreto/vibe_win_install/issues/2

**Comment by gqbay** [comment]
> Hello.
> 
> Try this
> #1
> 
> if it doesn't work, try this
> #2

Thanks!!! Finally got some free time to fix this. Yes! It was because of yolov3.cfg 
First time it was't  downloaded. And after I downloaded it manually, I also put it in the wrong directory :D Everything is works now! Going to learn pkg to fbx! Thanks a lot!!!!

**Comment by jangalasriramd7** [comment]
(venv_vibe) E:\MoCAP\VIBE>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 72, in main
    image_folder, num_frames, img_shape = video_to_images(video_file, return_info=True)
  File "E:\MoCAP\VIBE\lib\utils\demo_utils.py", line 195, in video_to_images
    subprocess.call(command)
  File "C:\Anaconda\envs\venv_vibe\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Anaconda\envs\venv_vibe\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda\envs\venv_vibe\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified


I'm getting the above error, after successfully installing all the libraries. Also I downloaded the yolov3.cfg and yolov3.weights manually from the #1 post. That is also not working for me. Can you please help me out from this.

**Comment by gqbay** [comment]
Try to double check yolov3.cfg and yolov3.weight
My mistake was: these 2 files was in the same folder. But you have to place
them separately ---> yolof3.cfg to users/your-name/.torch/config
And yolow3.weight to users/your-name/.torch/models

**Comment by Xushuolin** [comment]
> 
Does yolo go on C drive even though my vibe folder is on D drive?

**Comment by carlosedubarreto** [comment]
@Xushuolin its more related to the drive that has the "user" folder.
As far as I know you can choose this path
