### ISSUE TITLE
File no found when running

### ISSUE THREAD

**Issue by Farquaad56** [carlosedubarreto/vibe_win_install#8]
Hi, have got an error when i tried to run the demo i don't understand wish file missing and who to fix it

`(venv_vibe) D:\IA\vibe>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Images saved to "/tmp\sample_video_mp4"
Input video number of frames 300
Downloading files from https://pjreddie.com/media/files/yolov3.weights
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 93, in main
    yolo_img_size=args.yolo_img_size,
  File "C:\Users\xxx\anaconda3\envs\venv_vibe\lib\site-packages\multi_person_tracker\mpt.py", line 53, in __init__
    device=self.device, img_size=yolo_img_size, person_detector=True, video=True, return_dict=True
  File "C:\Users\xxx\anaconda3\envs\venv_vibe\lib\site-packages\yolov3\yolo.py", line 32, in __init__
    download_url(url, outdir)
  File "C:\Users\xxx\anaconda3\envs\venv_vibe\lib\site-packages\yolov3\yolo.py", line 11, in download_url
    subprocess.call(cmd)
  File "C:\Users\xxx\anaconda3\envs\venv_vibe\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\xxx\anaconda3\envs\venv_vibe\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\xxx\anaconda3\envs\venv_vibe\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable`

**Comment by Farquaad56** [comment]
solved by copy yolov3.weights and yolov3.cfg
i think you can add to run cmd in admin mode when we run .bat files

**Comment by carlosedubarreto** [comment]
Thanks for the input, I've added the information.
![image](https://user-images.githubusercontent.com/4061130/113757001-7ab20c00-96e8-11eb-9519-3e8bc46cb44e.png)

Have fun using it.
And if you want to use the data in 3d space, you can try the addon I've done last week that enables you to import the data into blender (now it only imports 1 character)

https://gumroad.com/l/mocap_import
you cen find it also in the github page 
https://github.com/carlosedubarreto/b3d_mocap_import

The gumroad option is ready to install
